### LOGIN 
 
 POST http://localhost:8000/api/v1/auth/jwt/create/
 Content-Type: application/json 
 Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MTczMjY4LCJpYXQiOjE3NjQxNzI5NjgsImp0aSI6IjBjMjYyYTIxNDIxMTQ5MWU5NzUyZmNkZjYxNjY0NDY4IiwidXNlcl9pZCI6IjEifQ.7CrRdAk5KbLBrcIukQnpfdrXyz6qU08QowbrNR2SvIc
 
 {
     "username": "namiyu",
     "password": "Rotterdam22*"
 }

### REFRESH 

    POST http://localhost:8000/api/v1/auth/jwt/refresh/
    Content-Type: application/json 
    
    {
        "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2NDI1OTM2OCwiaWF0IjoxNzY0MTcyOTY4LCJqdGkiOiI1NTk3MGY5NTg2ZDk0YWE2ODhlOTBhNzhhNDJhNjRlZSIsInVzZXJfaWQiOiIxIn0.bOrmL-JNca18hzxFEAkxniBhdh-gG5BAGFqVDa3G5zs"
    }

### PROTECTED  

    GET http://localhost:8000/api/v1/protected/
    Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MTczMjY4LCJpYXQiOjE3NjQxNzI5NjgsImp0aSI6IjBjMjYyYTIxNDIxMTQ5MWU5NzUyZmNkZjYxNjY0NDY4IiwidXNlcl9pZCI6IjEifQ.7CrRdAk5KbLBrcIukQnpfdrXyz6qU08QowbrNR2SvIc